-- 1) Confirm context
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

-- 2) Set context explicitly
USE ROLE TRAINING_ROLE;
USE DATABASE "USER$COBRA";
USE SCHEMA "PUBLIC";

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

-- 3) Create repo (fully-quoted object name)
CREATE OR REPLACE GIT REPOSITORY "DATA_5035_2026"
  API_INTEGRATION = GITHUB_API
  ORIGIN = 'https://github.com/gasullivan/data-5035-2026.git';

-- 4) Verify it exists (account-wide)
SHOW GIT REPOSITORIES IN ACCOUNT;

SHOW GIT REPOSITORIES IN SCHEMA "USER$COBRA"."PUBLIC";

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

-- Set context
USE ROLE TRAINING_ROLE;
USE DATABASE "USER$COBRA";
USE SCHEMA "PUBLIC";

-- Confirm context is now set
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

-- List repos and force-display results
SHOW GIT REPOSITORIES;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GIT REPOSITORIES IN ACCOUNT;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW INTEGRATIONS;

USE ROLE TRAINING_ROLE;
USE DATABASE "USER$COBRA";
USE SCHEMA "PUBLIC";

CREATE OR REPLACE GIT REPOSITORY "USER$COBRA"."PUBLIC"."DATA_5035_2026"
  API_INTEGRATION = GITHUB_API
  ORIGIN = 'https://github.com/gasullivan/data-5035-2026.git';


USE ROLE TRAINING_ROLE;
USE DATABASE "USER$COBRA";
USE SCHEMA "PUBLIC";

CREATE GIT REPOSITORY "DATA_5035_2026"
  API_INTEGRATION = GITHUB_API
  ORIGIN = 'https://github.com/gasullivan/data-5035-2026.git';


USE ROLE TRAINING_ROLE;
USE DATABASE "USER$COBRA";
USE SCHEMA "PUBLIC";

CREATE OR REPLACE TABLE "_perm_test" (id INT);
DROP TABLE "_perm_test";

USE ROLE TRAINING_ROLE;
USE DATABASE DATA5035;
USE SCHEMA PUBLIC;

CREATE OR REPLACE GIT REPOSITORY DATA_5035_2026
  API_INTEGRATION = GITHUB_API
  ORIGIN = 'https://github.com/gasullivan/data-5035-2026.git';

SHOW GIT REPOSITORIES IN SCHEMA DATA5035.PUBLIC;


USE ROLE TRAINING_ROLE;
USE DATABASE SNOWBEARAIR_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE GIT REPOSITORY DATA_5035_2026
  API_INTEGRATION = GITHUB_API
  ORIGIN = 'https://github.com/gasullivan/data-5035-2026.git';


SHOW GIT REPOSITORIES IN SCHEMA SNOWBEARAIR_DB.PUBLIC;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));